/*******************************************************************************
 * @file Buzzer.hpp
 * @brief Driver for the DEBUG_BUZZER transducer on PC14.
 *
 * The part fitted on Rev A is an **AT-0927-TT-6-R**: a *passive* magnetic
 * transducer, 2–4 Vpp, with a resonant frequency of 2730 Hz. Passive means it
 * produces no sound from a static logic level — the drive waveform must be
 * generated in firmware. Driving it at kResonantFreqHz is dramatically louder
 * than any other frequency.
 *
 * PC14 has no timer channel on this package, so there is no hardware PWM
 * option. The tone is generated by toggling the GPIO in a busy-wait loop
 * timed from the DWT cycle counter, which is the only mechanism with enough
 * resolution for a 183 µs half-period at 250 MHz SYSCLK.
 *
 * @warning beep() BLOCKS for its full duration and busy-waits the CPU. Under
 *          FreeRTOS it must only be called from the lowest-priority
 *          application task (the heartbeat task). Higher-priority tasks —
 *          above all the control task — still preempt it normally, so a short
 *          chirp from a priority-1 task costs nothing that matters. Never call
 *          it from an ISR, from the control task, or with a duration long
 *          enough to starve the idle task of its watchdog housekeeping.
 *
 * Usage:
 * @code
 *   Buzzer buzzer(DEBUG_BUZZER_GPIO_Port, DEBUG_BUZZER_Pin);
 *   buzzer.init();
 *   buzzer.chirp();                                  // short confirmation tone
 *   buzzer.beep(Buzzer::kResonantFreqHz, 500U);      // half-second tone
 * @endcode
 *
 * @author Integrated Motor Controller firmware team
 ******************************************************************************/

#pragma once

extern "C"
{
#include "stm32h5xx_hal.h"
}

#include <cstdint>

/*******************************************************************************
 * @brief Passive magnetic transducer driven by firmware-generated tones.
 ******************************************************************************/
class Buzzer final
{
public:
  /// Resonant frequency of the AT-0927-TT-6-R, in hertz. Loudest tone by a
  /// wide margin — use it unless you specifically want a quieter one.
  static constexpr uint32_t kResonantFreqHz = 2730U;

  /// Duration of the tone produced by chirp(), in milliseconds.
  static constexpr uint32_t kChirpMs = 60U;

  /// Lowest frequency accepted by beep(). Below this the half-period cycle
  /// count overflows the useful range of the busy-wait.
  static constexpr uint32_t kMinFreqHz = 20U;

  /**
   * @brief Construct a buzzer bound to one GPIO pin.
   *
   * @param port GPIO port the transducer is wired to.
   * @param pin  GPIO pin mask.
   */
  Buzzer(GPIO_TypeDef* port, uint16_t pin);

  /**
   * @brief Drive the pin low and enable the DWT cycle counter.
   *
   * Enabling DWT is idempotent and harmless if something else already did it.
   *
   * @return true on success; false if the cycle counter will not run, in which
   *         case beep() would busy-wait forever and is disabled.
   */
  bool init();

  /**
   * @brief Emit a tone.
   *
   * @param freqHz Tone frequency in hertz; clamped to at least kMinFreqHz.
   * @param durMs  Duration in milliseconds.
   *
   * @warning Blocks and busy-waits for durMs. See the file-level warning.
   */
  void beep(uint32_t freqHz, uint32_t durMs);

  /**
   * @brief Emit a short confirmation tone at the resonant frequency.
   *
   * @warning Blocks for kChirpMs. See the file-level warning.
   */
  void chirp();

  /**
   * @brief Force the drive pin low.
   *
   * Safe to call from anywhere, including an ISR. Does not block.
   */
  void silence();

private:
  /**
   * @brief Busy-wait for a number of core clock cycles.
   *
   * @param cycles Number of SYSCLK cycles to wait.
   */
  static void waitCycles(uint32_t cycles);

  GPIO_TypeDef* m_port;  ///< GPIO port the transducer is wired to.
  uint16_t      m_pin;   ///< GPIO pin mask.
  bool          m_ready; ///< true once init() confirmed the DWT counter runs.
};

/* EOF -----------------------------------------------------------------------*/
